name: echo
description: A graph based state management library in flutter with support for MVC & MVVM patterns
version: 0.0.1
repository: https://github.com/AdityaMotale/echo
issue_tracker: https://github.com/AdityaMotale/echo/issues
homepage: https://github.com/AdityaMotale/echo

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  paw: ^0.0.1 # logging

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.0.0