name: ecko
description: Ecko is a graph-based state management library for Flutter applications
version: 0.0.1
repository: https://github.com/AdityaMotale/ecko
issue_tracker: https://github.com/AdityaMotale/ecko/issues
homepage: https://github.com/AdityaMotale/ecko

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  paw: ^0.0.3 # logging

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
